version: "3.9"

services:
  api:
    build:
      context: .
    ports:
      - 80:80
    volumes:
      - ./config.py:/app/config
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
  migrations:
    build:
      context: .
    volumes:
      - ./config.py:/app/config
    depends_on:
      postgres:
        condition: service_healthy
    command:
      -  flask db upgrade
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: pavel2232
      POSTGRES_PASSWORD: 10203040Xx
      POSTGRES_DB: movie_app
    volumes:
      - ./app/postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "postgres_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5