DELETE http://127.0.0.1:5000/auth/3
Accept: application/json
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Im5hZGV6ZGEiLCJyb2xlIjoiQWRtaW4iLCJleHAiOjE2NjI3MjgxNTB9.UCnn5u_Xwe9lZd0ZcfTAHQnb49vTF77cC9K6_PQrdu4
###

GET http://127.0.0.1:5000/auth/
Content-Type: application/json
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Im5hZGV6ZGEiLCJyb2xlIjoiQWRtaW4iLCJleHAiOjE2NjI3MjgxNTB9.UCnn5u_Xwe9lZd0ZcfTAHQnb49vTF77cC9K6_PQrdu4


###

POST http://127.0.0.1:5000/user/
Content-Type: application/json

{
  "username": "nadezda",
  "password": "test",
  "role": "Admin"
}

###

POST http://127.0.0.1:5000/auth/
Content-Type: application/json

{
    "username": "nadezda",
    "password": "test"
}
